version: '3.9'
services:
  db:
    image: postgres:13-alpine
    ports:
    - 8081:5434
    volumes:
      - $PWD/test-pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DBNAME=test_db
      - POSTGRES_PASSWORD=admin
  app:
    build: .
    container_name: application
    ports:
    - 8080:8080
    command: python /app/test/app.py
    volumes:
      - ./:/app/test