version: '3.9'
services:
  db:
    image: postgres:12-alpine
    container_name: postgres
    ports:
    - 5434:5434
    volumes:
    - ./pg_data:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: test_db
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
  app:
    build: .
    container_name: application
    ports:
    - 8080:8080
    environment:
      POSTGRES_HOST: db
    restart: always
    links:
      - db